"""Session-scoped physical review persistence contract."""

from decimal import Decimal
from typing import Protocol

from app.application.dto.physical_review import (
    LatestFinalReviewItem, PhysicalReviewDetails, PhysicalReviewSummary,
    ReviewPopulationItem,
)
from app.domain.models import PhysicalReview, PhysicalReviewItem


class PhysicalReviewPort(Protocol):
    def get_active_draft(self) -> PhysicalReviewSummary | None: ...
    def get_review(self, review_id: str) -> PhysicalReviewDetails | None: ...
    def list_reviews(self) -> list[PhysicalReviewSummary]: ...
    def list_population(self) -> list[ReviewPopulationItem]: ...
    def add_draft_header(self, review: PhysicalReview) -> None: ...
    def add_items(self, items: list[PhysicalReviewItem]) -> None: ...
    def update_observed_quantity(self, review_item_id: str, value: Decimal | None) -> None: ...
    def discard_draft(self, review_id: str) -> None: ...
    def finalize_draft(self, review_id: str) -> None: ...
    def get_latest_final_items_for_analytics(self) -> list[LatestFinalReviewItem]: ...
