"""add core integrity constraints

Revision ID: bae33dc76391
Revises: fdaac4f8756e
Create Date: 2026-08-28 13:36:17.245924
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bae33dc76391'
down_revision: Union[str, None] = 'fdaac4f8756e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'uq_sds_documents_sds_product',
        'sds_documents',
        ['sds_id', 'product_id'],
    )
    op.drop_constraint(
        op.f('bhp_decisions_sds_id_fkey'),
        'bhp_decisions',
        type_='foreignkey',
    )
    op.create_foreign_key(
        'fk_bhp_decisions_sds_product',
        'bhp_decisions',
        'sds_documents',
        ['sds_id', 'product_id'],
        ['sds_id', 'product_id'],
    )
    op.create_index(
        'uq_sds_documents_one_current_per_product',
        'sds_documents',
        ['product_id'],
        unique=True,
        postgresql_where=sa.text("document_status = 'CURRENT'"),
    )
    op.create_index(
        'uq_bhp_decisions_one_current_per_sds',
        'bhp_decisions',
        ['sds_id'],
        unique=True,
        postgresql_where=sa.text("record_status = 'CURRENT'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'uq_bhp_decisions_one_current_per_sds',
        table_name='bhp_decisions',
        postgresql_where=sa.text("record_status = 'CURRENT'"),
    )
    op.drop_index(
        'uq_sds_documents_one_current_per_product',
        table_name='sds_documents',
        postgresql_where=sa.text("document_status = 'CURRENT'"),
    )
    op.drop_constraint(
        'fk_bhp_decisions_sds_product',
        'bhp_decisions',
        type_='foreignkey',
    )
    op.create_foreign_key(
        op.f('bhp_decisions_sds_id_fkey'),
        'bhp_decisions',
        'sds_documents',
        ['sds_id'],
        ['sds_id'],
    )
    op.drop_constraint(
        'uq_sds_documents_sds_product',
        'sds_documents',
        type_='unique',
    )
    # ### end Alembic commands ###
