"""initial core schema

Revision ID: fdaac4f8756e
Revises:
Create Date: 2026-08-28 13:24:35.901977
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fdaac4f8756e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_evidence',
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('relative_path', sa.String(), nullable=False),
    sa.Column('evidence_type', sa.Enum('EMAIL', 'DOCUMENT', 'PHOTO_SCAN', name='evidence_type_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('file_format', sa.Enum('MSG', 'PDF', 'JPG', 'JPEG', 'PNG', name='evidence_file_format_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('file_status', sa.Enum('AVAILABLE', 'MISSING', name='file_availability_status_values', native_enum=False, create_constraint=True), nullable=False),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_table('manufacturers',
    sa.Column('manufacturer_id', sa.String(), nullable=False),
    sa.Column('manufacturer_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('manufacturer_id')
    )
    op.create_table('usage_locations',
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('manufacturer_product_code', sa.String(), nullable=False),
    sa.Column('manufacturer_id', sa.String(), nullable=False),
    sa.Column('use_description', sa.String(), nullable=False),
    sa.Column('use_restriction', sa.String(), nullable=False),
    sa.Column('usage_status', sa.Enum('PENDING_APPROVAL', 'ACTIVE', 'REJECTED', 'INACTIVE', name='product_usage_status_values', native_enum=False, create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.manufacturer_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('product_usage_locations',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('quantity_value', sa.Numeric(), nullable=False),
    sa.Column('quantity_unit', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['usage_locations.location_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'location_id')
    )
    op.create_table('sds_documents',
    sa.Column('sds_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('relative_path', sa.String(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('revision', sa.String(), nullable=True),
    sa.Column('document_status', sa.Enum('CURRENT', 'ARCHIVED', name='sds_document_status_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('file_status', sa.Enum('AVAILABLE', 'MISSING', name='file_availability_status_values', native_enum=False, create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('sds_id')
    )
    op.create_table('bhp_decisions',
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('sds_id', sa.String(), nullable=False),
    sa.Column('decision_status', sa.Enum('APPROVED', 'REJECTED', name='bhp_decision_status_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('record_status', sa.Enum('CURRENT', 'SUPERSEDED', name='decision_record_status_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['decision_evidence.evidence_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['sds_id'], ['sds_documents.sds_id'], ),
    sa.PrimaryKeyConstraint('decision_id'),
    sa.UniqueConstraint('evidence_id')
    )
    op.create_table('safety_profiles',
    sa.Column('sds_id', sa.String(), nullable=False),
    sa.Column('product_definition', sa.String(), nullable=True),
    sa.Column('hazardous_classification_status', sa.Enum('YES', 'NO', 'NO_DATA', 'NOT_APPLICABLE', name='sp_hazardous_status_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('clp_classification_text', sa.String(), nullable=True),
    sa.Column('signal_word', sa.String(), nullable=True),
    sa.Column('hazard_statements', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('supplemental_hazard_statements', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('pbt_status', sa.Enum('YES', 'NO', 'NO_DATA', 'NOT_APPLICABLE', name='sp_pbt_status_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('vpvb_status', sa.Enum('YES', 'NO', 'NO_DATA', 'NOT_APPLICABLE', name='sp_vpvb_status_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('carcinogenicity_status', sa.Enum('YES', 'NO', 'NO_DATA', 'NOT_APPLICABLE', name='sp_carcinogenicity_status_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('germ_cell_mutagenicity_status', sa.Enum('YES', 'NO', 'NO_DATA', 'NOT_APPLICABLE', name='sp_mutagenicity_status_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reproductive_toxicity_status', sa.Enum('YES', 'NO', 'NO_DATA', 'NOT_APPLICABLE', name='sp_reproductive_status_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('endocrine_section_2_status', sa.Enum('YES', 'NO', 'NO_DATA', 'NOT_APPLICABLE', name='sp_endocrine_s2_status_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('endocrine_section_11_status', sa.Enum('YES', 'NO', 'NO_DATA', 'NOT_APPLICABLE', name='sp_endocrine_s11_status_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('skin_sensitization_status', sa.Enum('YES', 'NO', 'NO_DATA', 'NOT_APPLICABLE', name='sp_skin_sensitization_status_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('respiratory_sensitization_status', sa.Enum('YES', 'NO', 'NO_DATA', 'NOT_APPLICABLE', name='sp_respiratory_sensitization_status_values', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.Column('last_manual_edit_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sds_id'], ['sds_documents.sds_id'], ),
    sa.PrimaryKeyConstraint('sds_id')
    )
    op.create_table('sds_components',
    sa.Column('component_id', sa.String(), nullable=False),
    sa.Column('sds_id', sa.String(), nullable=False),
    sa.Column('component_name', sa.String(), nullable=False),
    sa.Column('cas_number', sa.String(), nullable=True),
    sa.Column('ec_number', sa.String(), nullable=True),
    sa.Column('reach_registration_number', sa.String(), nullable=True),
    sa.Column('concentration_text', sa.String(), nullable=True),
    sa.Column('classification_text', sa.String(), nullable=True),
    sa.Column('hazard_statements', postgresql.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['sds_id'], ['sds_documents.sds_id'], ),
    sa.PrimaryKeyConstraint('component_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sds_components')
    op.drop_table('safety_profiles')
    op.drop_table('bhp_decisions')
    op.drop_table('sds_documents')
    op.drop_table('product_usage_locations')
    op.drop_table('products')
    op.drop_table('usage_locations')
    op.drop_table('manufacturers')
    op.drop_table('decision_evidence')
    # ### end Alembic commands ###
